apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-mesh
  namespace: aurix-platform
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/part-of: aurix-platform
    - podSelector: {}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/part-of: aurix-platform
    - podSelector: {}
  policyTypes:
  - Ingress
  - Egress
